### PR TITLE
ronskie 🍉

### PR DESCRIPTION
**Pull request by Ronskie0804**
adding my name to contributor list

### CODE REVIEW

**Comment by Ronskie0804** [comment]
why did I delete it? and what should I replace it with? sorry I'm just before I make the repo I hope you can help me..

**Comment by thilinaabey** [comment]
No need I will fix it

**Comment by Ronskie0804** [comment]
ok thanks 
Do you know how to create an oss project that can contribute to the tea protocol?

**Comment by thilinaabey** [comment]
sync main to fork or fork again. then change the name to your name. at line 55 in readme.md

**Comment by Ronskie0804** [comment]
What should I replace the open source project with in your name?for example i replaced learning open source

**Pull request merged**
